### ISSUE TITLE
Possible improvement for pollen

### ISSUE THREAD

**Issue by golles** [huizebruin/Home-Assistant-Config#8]
Hi, I found your pollen integration and I wanted to let you know that I'm really happy you shared this, I copied it and made some improvements, maybe interesting for you as well? Pick what you like, discard what you don't 😉

Improvements:
- It uses the location from your home (no longer need to store the URL in secrets)
- It uses the message as a value, yours has a version but I don't see that in the JSON
- The rest sensor creates a data sensor with all data
- For each species another sensor is created, with all the specific details as attributes
- You seem to have mixed weeds and grass (Not sure if this is a mistake or done on purpose)
- Better translation for Moderate

I've got a strong preference for attributes over different sensors, as it feels like polluting to create sensors for things that could be an attribute also there is no longer a link between the sensors. 
Also if you click on one of these entities, the more-info will be shown and there you see all the attributes, I personally find that nice/useful to have a clean UI and more information just one click away:
<img width="385" alt="Schermafbeelding 2021-05-13 om 14 43 01" src="https://user-images.githubusercontent.com/2211503/118127194-addb6f80-b3f9-11eb-96ff-86de0227080f.png">

pollen.yaml
```yaml
sensor:
  - platform: rest
    name: pollen_data
    scan_interval: 900
    resource_template: https://api.ambeedata.com/latest/pollen/by-lat-lng?lat={{ state_attr("zone.home", "latitude") }}&lng={{ state_attr("zone.home", "longitude") }}
    value_template: >-
      {{ value_json.message}}
    headers:
      content-type: application/json
      x-api-key: !secret ambee-api
    json_attributes_path: data[0]
    json_attributes:
      - Count
      - Risk
      - Species
      - updatedAt

  - platform: template
    sensors:
      pollen_bomen:
        friendly_name: Bomen
        icon_template: mdi:tree
        value_template: >-
          {% set state = state_attr("sensor.pollen_data", "Risk").tree_pollen %}
          {% if state == "Low" %} Weinig
          {% elif state == "Moderate"%} Matig
          {% elif state == "High"%} Hoog
          {% elif state == "Very High"%} Zeer hoog
          {% else %}Onbekend{% endif %}
        attribute_templates:
          Totaal: >-
            {{ state_attr("sensor.pollen_data", "Count").tree_pollen }} /m³
          Els: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Alder }} /m³
          Berk: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Birch }} /m³
          Coniferen: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Cypress }} /m³
          Iep: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Elm }} /m³
          Hazelaar: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Hazel }} /m³
          Eik: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Oak }} /m³
          Den: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Pine }} /m³
          Plataan: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree.Plane }} /m³
          Populier: >-
            {{ state_attr("sensor.pollen_data", "Species").Tree["Poplar / Cottonwood"] }} /m³

      pollen_grassen:
        friendly_name: Grassen
        icon_template: mdi:grass
        value_template: >-
          {% set state = state_attr("sensor.pollen_data", "Risk").grass_pollen %}
          {% if state == "Low" %} Weinig
          {% elif state == "Moderate"%} Matig
          {% elif state == "High"%} Hoog
          {% elif state == "Very High"%} Zeer hoog
          {% else %}Onbekend{% endif %}
        attribute_templates:
          Totaal: >-
            {{ state_attr("sensor.pollen_data", "Count").grass_pollen }} /m³
          Gramineae: >-
            {{ state_attr("sensor.pollen_data", "Species").Grass["Grass / Poaceae"] }} /m³

      pollen_onkruiden:
        friendly_name: Onkruiden
        icon_template: mdi:grass
        value_template: >-
          {% set state = state_attr("sensor.pollen_data", "Risk").weed_pollen %}
          {% if state == "Low" %} Weinig
          {% elif state == "Moderate"%} Matig
          {% elif state == "High"%} Hoog
          {% elif state == "Very High"%} Zeer hoog
          {% else %}Onbekend{% endif %}
        attribute_templates:
          Totaal: >-
            {{ state_attr("sensor.pollen_data", "Count").weed_pollen }} /m³
          Amaranten/Ganzenvoet: >-
            {{ state_attr("sensor.pollen_data", "Species").Weed.Chenopod }} /m³
          Bijvoet: >-
            {{ state_attr("sensor.pollen_data", "Species").Weed.Mugwort }} /m³
          Brandnetel: >-
            {{ state_attr("sensor.pollen_data", "Species").Weed.Nettle }} /m³
          Ambrosia: >-
            {{ state_attr("sensor.pollen_data", "Species").Weed.Ragweed }} /m³

```

Curious to hear your feedback, also feel free to close this issue whenever you want
